name: First Workflow
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Echo Hello World
        run: echo "hello world"
      - name: Create file
        run: |
          touch hello.txt
          echo "haha what's up" >> hello.txt
          cat hello.txt
      - name: Create another file
        run: |
          chmod +x curl.sh
          ./curl.sh
          ls
      - name: Upload using Actions as Workflow Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: dragon.txt

  second_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Download Artifact using Actions
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
      - name: Display artifact contents
        run: cat dragon.txt
      
  third_job:
    runs-on: ubuntu-latest
    needs: [first_job, second_job]
    steps:
      - name: Print Goodbye
        run: echo "Goodbye"
